careercup/CtCI-6th-Edition-Python

Chapter4/42MinimalTree.py

chapter 4 solutions

---

Chapter4/42MinimalTree.py

Gives a better understanding of the tree if we print the node along with its left and right child

Printing node of binary tree with left and right child for better visualization

---

Chapter 1/2_Check Permutation/CheckPermutation.py

Current solution runs in O(nlogn)
Suggesting O(n) solution

suggesting linear time solution

---

Chapter4/41RouteBetweenNodes.py

It is BFS and not DFS in this algorithm

Fix name function

---

Chapter8/81TripleStep.py
Chapter8/82RobotGrid.py

- Added memoized and non-memoized  solutions

Added Implementation for 8.2

---

Chapter8/81TripleStep.py
Chapter8/84PowerSet.py

added both the recursive and the combinatoric solution.

Added implementation for 8.4

---

Chapter8/81TripleStep.py
Chapter8/87PermutationsWithoutDups.py

87 permutations without dups

---

Chapter1/3_URLify/URLify.py

This version of the algorithm takes and returns strings (as the question describes) rather than lists. Hoping to show how to deal with string inputs. Thanks so much for these solutions.

Update URLify.py to use string input and output

---

Chapter1/1_Is Unique/IsUnique.py

Not to be stickler or over-optimizer, but in the spirit of foster best practices of Python through education material I have to say according to my benchmark using `timeit` module, `[False] * number` in 3 orders of magnitude faster even in small number such as 128, to general best practice is to use this instead of a for loop to initialize an array with fix value. 
And doing so in great educational materials like yours would hopefully make people more aware of such good syntaxes.

C01_P01 - Perf best practice in isUnique.py

---

chapter_01/p01_is_unique.py

I add the test cases for the solution of C01-P01.
Because there was no test case for "if" at line7.
(This is the first time for me to send a pull request.
If you notice anything, please inform to me. I would like to fix it.)

fix(C01_P01): add more test cases

---

chapter_04/p06_successor.py

Added tests to check the 'in order' next node for problem p06 in chapter 4.

feature(C04_P06): added tests

---

chapter_04/p11_random_node.py

https://github.com/careercup/CtCI-6th-Edition-Python/pull/147#discussion_r554507642 
A possible solution for this :)

feature(C04_P11): have delete method be completely part of class

---

chapter_01/p01_is_unique.py

Hello,
First of all, thank you for this repository! It helps me a lot. 
While I was reading the book's solutions, I have found this one. So, this PR adds a solution for the second part of the question: 
> What if you cannot use additional data structures?
----
**Note:** I can squash commits if necessary. Let me know.
**Note-2:** I have one suggestion. Since you support using pytest, I think it would be better to use [parametrized methods](https://docs.pytest.org/en/stable/parametrize.html) and variables instead of one test with two loops. When you parameterize, you will have failing tests for a specific method.

update(C01_P01): Added bitwise solution

---

chapter_08/p10_paint_fill.py

This PR adds python implementation for **8.10 Paint Fill Problem in Chapter 8**

feature(C08_P10): added solution and tests

---

chapter_08/p14_boolean_evaluation.py

This PR adds python implementation for **8.14 Boolean Evaluation Problem in Chapter 8.**

C08_P14: added solution and tests

---

chapter_05/p02_binary_to_string.py

Here is an alternate solution which in my opinion is a bit easier.

Branch chap5p2

---

chapter_05/p01_insertion.py

Added a solution `chapter_05/p01_insertion.py` since the original solution is a bit hard to read and understand for me. I hope this solution will be helpful for people in the same situation.
By the way, I personally think we should change the test cases because the question in the book says _"You are given two 32-bit __numbers__, N and M, and two bit positions, i and j. (question continues)"_. So I think the input of the test case should be __numbers(int)__, not string. My understanding might be weird or wrong since I'm not native speaker.

feature (ch05_p01): add easy-to-understand solution

---

chapter_01/p03_urlify.py

As pointed out by @bdalal in #206, this function wasn't properly handling trailing spaces in the input.
I've updated the test case to test this situation and fixed the function.
Closes #206

fix(C01_P03): fix bug in `urlify_algo`

---

chapter_01/p01_is_unique.py

Adds a new function called **is_unique_chars_using_set**, that uses a set to solve the problem.
Also adds the function to the list **test_functions** in the unittest function.
It was formatted using black, and passes all the current tests.

feature(C01_P01): add solution that uses a set

---

chapter_01/p07_rotate_matrix.py

Added an alternate pythonic solution that solves the problem without creating multiple for loops.
Used `zip` on the matrix itself to create the new rows, then used `reverse` to get them in the correct order.
I think the time complexity for this solution is worse than the existing pythonic solution, but not sure how important big O is for considering solutions here.
It was formatted with black and passes all the current tests

feature(C01_P07): Add alternate pythonic solution

---

chapter_01/p04_palindrome_permutation.py

Thank you for your amazing repository.
I added a bit-wise solution for Palindrome Permutation problem based on the Solution#3 of the book.
Please let me know if it needs change

feature(C01_P04): Add a bit wise solution
